# Generated by Django 2.2.1 on 2019-05-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='disponivel',
            new_name='novidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.PositiveIntegerField(),
        ),
    ]
