# Generated by Django 2.2.1 on 2019-05-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20190518_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
