# Generated by Django 2.2.1 on 2019-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_produto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='outraCategoria',
            field=models.BooleanField(default=False),
        ),
    ]
