# Generated by Django 2.2.1 on 2019-05-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('sobrenome', models.CharField(db_index=True, max_length=200)),
                ('email', models.CharField(db_index=True, max_length=200)),
                ('senha', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='nota',
            field=models.IntegerField(db_index=True),
        ),
    ]
